In [1]:
import os
import polars as pl

In [2]:
# Getting CSV files from raw data dir
files = list(filter(lambda x: x.endswith(".csv"), os.listdir("./../data/raw")))

In [10]:
for filepath in files:
    df = pl.read_csv(f"./../data/raw/{filepath}", n_rows=5)
    assert df.shape[0] == 5, "Shape different than expected"

In [3]:
files

['olist_geolocation_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_sellers_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_products_dataset.csv',
 'product_category_name_translation.csv',
 'olist_orders_dataset.csv',
 'olist_customers_dataset.csv']

In [65]:
files[0]

'olist_geolocation_dataset.csv'

In [66]:
df = pl.read_csv(f"./../data/raw/{files[0]}")

In [67]:
df.dtypes

[Int64, Float64, Float64, String, String]

In [68]:
df.head()

shape: (5, 5)
┌───────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_ ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ prefix                ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ ---                   ┆ f64             ┆ f64             ┆ str              ┆ str               │
│ i64                   ┆                 ┆                 ┆                  ┆                   │
╞═══════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 1037                  ┆ -23.545621      ┆ -46.639292      ┆ sao paulo        ┆ SP                │
│ 1046                  ┆ -23.546081      ┆ -46.64482       ┆ sao paulo        ┆ SP                │
│ 1046                  ┆ -23.546129      ┆ -46.642951      ┆ sao paulo        ┆ SP                │
│ 1041                  ┆ -23.544392      ┆ -46.639499      ┆ sao paulo        ┆ SP                │
│ 1035                  ┆ -23.541578      ┆ -46.641607      ┆ sao paulo        ┆ SP                │
└───────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘

In [69]:
df.columns

['geolocation_zip_code_prefix',
 'geolocation_lat',
 'geolocation_lng',
 'geolocation_city',
 'geolocation_state']

In [60]:
df.select(
    pl.col("product_category_name")
    .sort_by(pl.col("product_weight_g"), descending=True)
    .first()
)

shape: (1, 1)
┌───────────────────────┐
│ product_category_name │
│ ---                   │
│ str                   │
╞═══════════════════════╡
│ bebes                 │
└───────────────────────┘

In [58]:
df.select(pl.col("product_weight_g").max())

shape: (1, 1)
┌──────────────────┐
│ product_weight_g │
│ ---              │
│ i64              │
╞══════════════════╡
│ 40425            │
└──────────────────┘